stages:
  - build
  - test

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm install
    - npm run build

test_website:
  image: alpine:latest
  stage: test
  script:
    - npm ci
    - npm run test