stages:
  - build
  - test

variables:
  CHROME_BIN: "/usr/bin/chromium-browser"

build_website:
  image: node:22-alpine
  stage: build
  script:
    - npm install
    - npm run build

test_website:
  image: node:22-alpine3.18
  stage: test
  before_script:
    - apk add --no-cache chromium
    - chromium-browser --version
  script:
    - npm ci
    - npm run test


lint:
  image: node:22-alpine3.18
  stage: .pre
  script:
    - npm ci
    - npm run test