stages:
  - build
  - test

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm install
    - npm run build

test_website:
  image: node:22-alpine
  stage: test
  script:
    - apk update
    - apk add --no-cache chromium
    - chromium-browser --version
    - npm install
    - npm run test